services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:  
      - 3000:3000
    volumes:
      - ./api:/app
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./client:/app
    depends_on:
      - api
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db